name: dyvi
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch=2.5.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - matplotlib
  - zarr
  - h5py
  - hydra-core
  - einops
  - tqdm
  - cmake
  - huggingface_hub
  - natsort
  - lightning
  - termcolor
  - pip:
      - wandb
